In [19]:
using Pkg; Pkg.activate(".");
using Convex
using SCS
c = 5*rand(7)

  Activating project at `~/Convex_Opt`


7-element Vector{Float64}:
 3.331652593494267
 1.3446507456196781
 1.4443267805526894
 4.017412761364381
 1.8928162640968693
 0.8082266400792559
 0.3316540569330001

In [46]:
c = 5*rand(7)

x = Variable(7)
objective = c'*x

cons = [
    ones(7)'*x <= 4,
    x >= 0,
    x <= 1
]



optimization = maximize(objective, cons)
solve!(optimization, SCS.Optimizer())
res = x.value
print(c'*res)

res





[12.741358894957362;;]------------------------------------------------------------------
	       SCS v3.2.1 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 8, constraints m: 16
cones: 	  z: primal zero / dual free vars: 1
	  l: linear vars: 15
settings: eps_abs: 1.0e-04, eps_rel: 1.0e-04, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 29, nnz(P): 0
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 4.67e+01  2.95e+00  1.25e+02 -8.15e+01  1.00e-01  8.19e-05 
    50| 2.65e-05  4.82e-05  3.52e-07 -1.27e+01  1.00e-01  1.30e-04 
-----------------

7×1 Matrix{Float64}:
  1.0000126509186666
 -6.319427376440264e-7
  0.9999932684538899
  0.99999571257118
 -2.648922244543348e-5
  1.6198350224925764e-5
  0.9999974683251368

In [51]:
###Trial
class_numbers = Dict("6.006"=>1, "6.042"=>2, "6.009"=>3, "6.046"=>4, "6.031"=>5, "18.600"=>6, "6.041"=>7,
"6.008"=>8, "comp_bio"=>9, "NLP"=>10, "comp_vision"=>11, "graphics"=>12, "optimization"=>13, 
    "script_analysis"=>14, "intro_to_acting"=>15, "psych"=>16)

taken = [1 1 1 0 0 1 0 0 0 0 0 1 0 0 0 1]

requirements = [([1], 1), ([2], 1), ([3], 1), ([4], 1), ([5], 1), ([6, 7, 8], 1), ([9, 10, 11, 12, 13], 2), 
    ([14, 15, 16], 2)]

remaining_reqs = Dict()

for (ind, req) in enumerate(requirements)
    remaining = req[2]
    for class in req[1]
        if taken[class] == 1
            remaining -= 1
            if remaining == 0
                break
            end
            
        end
        
    end
    remaining_reqs[ind] = remaining
end

remaining_reqs





Dict{Any, Any} with 8 entries:
  5 => 1
  4 => 1
  6 => 0
  7 => 1
  2 => 0
  8 => 1
  3 => 0
  1 => 0

In [74]:
c = 7*rand(16)
time_vec = 7*ones(16) + 7*rand(16)
c

16-element Vector{Float64}:
 0.22327455170845734
 5.366756156813789
 6.762908504954667
 3.5083544600567538
 1.3921499506438069
 1.0675555929509664
 0.5746663757775152
 1.5578789431072044
 5.7001686412239145
 1.5519382798232437
 6.782202747045394
 3.918740563557935
 4.365468714002073
 4.4510527478151465
 5.304203136247391
 1.0498175474957545

In [75]:
x = Variable(16)
objective = c'*x
t = 50
constr = [
    x >= 0,
    x <= 1,
    time_vec'*x <= t
    
]
for (class, status) in enumerate(taken)
    
    if status == 1
        
        push!(constr, (x[class] == 0))    
    end   
end


for (ind, req) in enumerate(requirements)
    length = size(req[1])[1]
    
    req_array = Array{Convex.AbstractExpr}(undef, length)
    for i in 1:length[1]
        req_array[i] = x[req[1][i]]
        
    end
    push!(constr, (sum(req_array) >= remaining_reqs[ind]))
end


optimization = maximize(objective, constr)
solve!(optimization, SCS.Optimizer())
res = x.value
print(c'*res)

res





[20.307698177221248;;]------------------------------------------------------------------
	       SCS v3.2.1 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 17, constraints m: 48
cones: 	  z: primal zero / dual free vars: 7
	  l: linear vars: 41
settings: eps_abs: 1.0e-04, eps_rel: 1.0e-04, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 87, nnz(P): 0
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.93e+02  7.65e+00  8.38e+01 -6.29e+01  1.00e-01  1.23e-04 
   200| 1.19e-03  1.48e-04  1.15e-03 -2.03e+01  1.00e-01  5.53e-04 
----------------

16×1 Matrix{Float64}:
 2.887436872336651e-8
 6.332203407334908e-8
 4.577526683621046e-8
 1.0000247624346064
 1.0000180005704848
 1.4511822939629311e-8
 1.391093402919218e-5
 1.631641131747948e-5
 0.5824455804005116
 2.9576215988435544e-5
 1.0000357054093263
 3.6044004344138584e-8
 2.8743155269800956e-5
 1.9488150763796928e-5
 1.0000194935717865
 9.716792512448966e-9

In [76]:
final_vector = round.(res, digits = 0)

16×1 Matrix{Float64}:
 0.0
 0.0
 0.0
 1.0
 1.0
 0.0
 0.0
 0.0
 1.0
 0.0
 1.0
 0.0
 0.0
 0.0
 1.0
 0.0

In [77]:
time_vec[4] + time_vec[5] + time_vec[9] + time_vec[11] + time_vec[15]

54.60584579911304

In [78]:
time_vec'*res

1×1 adjoint(::Vector{Float64}) with eltype Float64:
 49.998805938308834